# Generated by Django 3.1.5 on 2021-01-29 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(upload_to='input_images/<django.db.models.fields.related.ForeignKey>')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('output_image', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('finished', 'Finished')], default='new', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedFaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('detection_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.detectionimages')),
            ],
        ),
    ]
